### ISSUE TITLE
Crashes when folder selected

### ISSUE THREAD

**Issue by matthewblott** [b0o/nvim-tree-preview.lua#1] opened 2024-04-28 10:30 UTC
As described above. If the preview window is opened and I navigate through the files as soon as a directory is selected it crashes. Here's a screenshot:

![Screenshot 2024-04-28 at 11 27 46](https://github.com/b0o/nvim-tree-preview.lua/assets/1231417/909210ee-e49e-43a5-90f0-85b69d149fef)

Other than that, the plugin is great!

**Comment by b0o** [comment] 2024-04-28 10:34
Oops. I think the issue is that you’re not on neovim nightly. I am using some new APIs.

**Comment by b0o** [comment] 2024-04-28 10:35
I will try to make it more backwards compatible tomorrow.

**Comment by matthewblott** [comment] 2024-04-28 10:38
@b0o Yeah no biggie, I can press escape but it just makes for a smoother experience. Happy to wait :-)

**Comment by b0o** [comment] 2024-04-29 03:12
Should be fixed, mind giving it a try?

**Comment by matthewblott** [comment] 2024-05-01 21:53
@b0o This works a treat now, great work thanks :-)

**Closed as completed** 2024-05-01 22:52 UTC
Labels: bug
